timeout: 5

/MONOLITH
    # Boot the kernel using the multiboot2 protocol.
    protocol: multiboot2
    kernel_path: $boot():/boot/kernel.bin.gz
    cmdline: init=file:/system/desktop
    module_path: $boot():/boot/initrd.tar.gz
    module_string: /boot/initrd.tar.gz
