/*
 * Copyright (c) 2025, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#define SYSCALL_EXIT 0
#define SYSCALL_RSRC_OPEN 3
#define SYSCALL_RSRC_CLOSE 4
#define SYSCALL_RSRC_DUP 5
#define SYSCALL_RSRC_LIST 6
#define SYSCALL_RSRC_READ 7
#define SYSCALL_RSRC_WRITE 8
#define SYSCALL_RSRC_REMOVE 9
#define SYSCALL_RSRC_LOOKUP 10
#define SYSCALL_RSRC_DESCRIBE 11
#define SYSCALL_RSRC_SEEK 12
#define SYSCALL_RSRC_CONTROL 13
#define SYSCALL_SLEEP 14
#define SYSCALL_GET_TICKS 15
#define SYSCALL_ALLOC_PAGES 16
#define SYSCALL_SPAWN_TASK 17
#define SYSCALL_RSRC_MMAP 18
#define SYSCALL_RSRC_CREATE 19
#define SYSCALL_UNMAP_PAGES 30
