/*
 * Copyright (c) 2025, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#define SYSCALL_EXIT 0
#define SYSCALL_SLEEP 1
#define SYSCALL_GET_TICKS 2
#define SYSCALL_ALLOC_PAGES 3
#define SYSCALL_UNMAP_PAGES 4
#define SYSCALL_RSRC_OPEN 5
#define SYSCALL_RSRC_CLOSE 6
#define SYSCALL_RSRC_DUP 7
#define SYSCALL_RSRC_LIST 8
#define SYSCALL_RSRC_READ 9
#define SYSCALL_RSRC_WRITE 10
#define SYSCALL_RSRC_REMOVE 11
#define SYSCALL_RSRC_LOOKUP 12
#define SYSCALL_RSRC_DESCRIBE 13
#define SYSCALL_RSRC_SEEK 14
#define SYSCALL_RSRC_CONTROL 15
#define SYSCALL_RSRC_MMAP 16
#define SYSCALL_FILE_CREATE 17
#define SYSCALL_IPC_CHANNEL_CREATE 18
#define SYSCALL_SHM_CREATE 19
#define SYSCALL_TASK_CREATE 20
#define SYSCALL_PIPE_CREATE 21
#define SYSCALL_RSRC_POLL 22
#define SYSCALL_CHCWD 23
#define SYSCALL_DIR_CREATE 24
