name: Build & Release ISO

on:
  push:
    branches: [main]
    paths:
      - "boot/**"
      - "kernel/**"
      - "userspace/**"
      - "libs/**"
      - "scripts/**"
      - "shared/**"
      - "Makefile"

jobs:
  build:
    runs-on: ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev \
            texinfo libisl-dev nasm qemu-system xorriso mtools \
            grub-pc-bin grub-common git bash

      - name: Build
        run: |
          make ARCH=pc/x64 iso
          make ARCH=pc/ia32 iso

          mkdir -p dist/release
          cp build/pc_x64/monolith-x64.iso dist/release/monolith-x64.iso
          cp build/pc_ia32/monolith-ia32.iso dist/release/monolith-ia32.iso

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: monolith-isos
          path: dist/release/*

  release:
    runs-on: ubuntu
    needs: build

    steps:
      - name: Download built ISO
        uses: actions/download-artifact@v3
        with:
          name: monolith-isos
          path: dist/release

      - name: Forgejo Release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: nightly-${{ forgejo.run_number }}
          name: Nightly Build ${{ forgejo.run_number }}
          prerelease: true
          release-dir: dist/release
          override: true
