timeout: 5

/MONOLITH
    # Boot the kernel using the Limine boot protocol.
    protocol: limine
    kernel_path: $boot():/boot/kernel.bin.gz
    cmdline: init=system:/desktop
    module_path: $boot():/boot/initrd.tar.gz
