/*
 * Copyright (c) 2026, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <unistd.h>

typedef enum : uint8_t {
    INPUT_EVENT_NONE = 0,
    INPUT_EVENT_KEYBOARD,
    INPUT_EVENT_MOUSE,
} input_event_type_t;

typedef enum : uint8_t {
    INPUT_KEYACTION_UP = 2,
    INPUT_KEYACTION_DOWN = 1,
    INPUT_KEYACTION_HOLD = 0,
} input_keyboard_action_t;

typedef enum : uint8_t {
    INPUT_KEYBOARD_SCANCODE_NULL = 0,
    INPUT_KEYBOARD_SCANCODE_ESCAPE = 0x01,
    INPUT_KEYBOARD_SCANCODE_1 = 0x02,
    INPUT_KEYBOARD_SCANCODE_2 = 0x03,
    INPUT_KEYBOARD_SCANCODE_3 = 0x04,
    INPUT_KEYBOARD_SCANCODE_4 = 0x05,
    INPUT_KEYBOARD_SCANCODE_5 = 0x06,
    INPUT_KEYBOARD_SCANCODE_6 = 0x07,
    INPUT_KEYBOARD_SCANCODE_7 = 0x08,
    INPUT_KEYBOARD_SCANCODE_8 = 0x09,
    INPUT_KEYBOARD_SCANCODE_9 = 0x0A,
    INPUT_KEYBOARD_SCANCODE_0 = 0x0B,
    INPUT_KEYBOARD_SCANCODE_MINUS = 0x0C,
    INPUT_KEYBOARD_SCANCODE_EQUALS = 0x0D,
    INPUT_KEYBOARD_SCANCODE_BACKSPACE = 0x0E,
    INPUT_KEYBOARD_SCANCODE_TAB = 0x0F,
    INPUT_KEYBOARD_SCANCODE_Q = 0x10,
    INPUT_KEYBOARD_SCANCODE_W = 0x11,
    INPUT_KEYBOARD_SCANCODE_E = 0x12,
    INPUT_KEYBOARD_SCANCODE_R = 0x13,
    INPUT_KEYBOARD_SCANCODE_T = 0x14,
    INPUT_KEYBOARD_SCANCODE_Y = 0x15,
    INPUT_KEYBOARD_SCANCODE_U = 0x16,
    INPUT_KEYBOARD_SCANCODE_I = 0x17,
    INPUT_KEYBOARD_SCANCODE_O = 0x18,
    INPUT_KEYBOARD_SCANCODE_P = 0x19,
    INPUT_KEYBOARD_SCANCODE_LBRACKET = 0x1A,
    INPUT_KEYBOARD_SCANCODE_RBRACKET = 0x1B,
    INPUT_KEYBOARD_SCANCODE_ENTER = 0x1C,
    INPUT_KEYBOARD_SCANCODE_LCTRL = 0x1D,
    INPUT_KEYBOARD_SCANCODE_A = 0x1E,
    INPUT_KEYBOARD_SCANCODE_S = 0x1F,
    INPUT_KEYBOARD_SCANCODE_D = 0x20,
    INPUT_KEYBOARD_SCANCODE_F = 0x21,
    INPUT_KEYBOARD_SCANCODE_G = 0x22,
    INPUT_KEYBOARD_SCANCODE_H = 0x23,
    INPUT_KEYBOARD_SCANCODE_J = 0x24,
    INPUT_KEYBOARD_SCANCODE_K = 0x25,
    INPUT_KEYBOARD_SCANCODE_L = 0x26,
    INPUT_KEYBOARD_SCANCODE_SEMICOLON = 0x27,
    INPUT_KEYBOARD_SCANCODE_APOSTROPHE = 0x28,
    INPUT_KEYBOARD_SCANCODE_BACKTICK = 0x29,
    INPUT_KEYBOARD_SCANCODE_LSHIFT = 0x2A,
    INPUT_KEYBOARD_SCANCODE_BACKSLASH = 0x2B,
    INPUT_KEYBOARD_SCANCODE_Z = 0x2C,
    INPUT_KEYBOARD_SCANCODE_X = 0x2D,
    INPUT_KEYBOARD_SCANCODE_C = 0x2E,
    INPUT_KEYBOARD_SCANCODE_V = 0x2F,
    INPUT_KEYBOARD_SCANCODE_B = 0x30,
    INPUT_KEYBOARD_SCANCODE_N = 0x31,
    INPUT_KEYBOARD_SCANCODE_M = 0x32,
    INPUT_KEYBOARD_SCANCODE_COMMA = 0x33,
    INPUT_KEYBOARD_SCANCODE_PERIOD = 0x34,
    INPUT_KEYBOARD_SCANCODE_SLASH = 0x35,
    INPUT_KEYBOARD_SCANCODE_RSHIFT = 0x36,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_ASTERISK = 0x37,
    INPUT_KEYBOARD_SCANCODE_LALT = 0x38,
    INPUT_KEYBOARD_SCANCODE_SPACE = 0x39,
    INPUT_KEYBOARD_SCANCODE_CAPSLOCK = 0x3A,
    INPUT_KEYBOARD_SCANCODE_F1 = 0x3B,
    INPUT_KEYBOARD_SCANCODE_F2 = 0x3C,
    INPUT_KEYBOARD_SCANCODE_F3 = 0x3D,
    INPUT_KEYBOARD_SCANCODE_F4 = 0x3E,
    INPUT_KEYBOARD_SCANCODE_F5 = 0x3F,
    INPUT_KEYBOARD_SCANCODE_F6 = 0x40,
    INPUT_KEYBOARD_SCANCODE_F7 = 0x41,
    INPUT_KEYBOARD_SCANCODE_F8 = 0x42,
    INPUT_KEYBOARD_SCANCODE_F9 = 0x43,
    INPUT_KEYBOARD_SCANCODE_F10 = 0x44,
    INPUT_KEYBOARD_SCANCODE_NUMLOCK = 0x45,
    INPUT_KEYBOARD_SCANCODE_SCROLLLOCK = 0x46,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_7 = 0x47,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_8 = 0x48,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_9 = 0x49,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_MINUS = 0x4A,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_4 = 0x4B,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_5 = 0x4C,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_6 = 0x4D,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_PLUS = 0x4E,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_1 = 0x4F,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_2 = 0x50,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_3 = 0x51,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_0 = 0x52,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_PERIOD = 0x53,
    INPUT_KEYBOARD_SCANCODE_SYSRQ = 0x54,
    INPUT_KEYBOARD_SCANCODE_ISO_EXTRA = 0x56,
    INPUT_KEYBOARD_SCANCODE_F11 = 0x57,
    INPUT_KEYBOARD_SCANCODE_F12 = 0x58,
    INPUT_KEYBOARD_SCANCODE_RALT = 0x60,
    INPUT_KEYBOARD_SCANCODE_RCTRL = 0x61,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_ENTER = 0x62,
    INPUT_KEYBOARD_SCANCODE_KEYPAD_SLASH = 0x63,
    INPUT_KEYBOARD_SCANCODE_HOME = 0x64,
    INPUT_KEYBOARD_SCANCODE_UP = 0x65,
    INPUT_KEYBOARD_SCANCODE_PAGE_UP = 0x66,
    INPUT_KEYBOARD_SCANCODE_LEFT = 0x67,
    INPUT_KEYBOARD_SCANCODE_RIGHT = 0x68,
    INPUT_KEYBOARD_SCANCODE_END = 0x69,
    INPUT_KEYBOARD_SCANCODE_DOWN = 0x6A,
    INPUT_KEYBOARD_SCANCODE_PAGE_DOWN = 0x6B,
    INPUT_KEYBOARD_SCANCODE_INSERT = 0x6C,
    INPUT_KEYBOARD_SCANCODE_DELETE = 0x6D,
    INPUT_KEYBOARD_SCANCODE_PRINT_SCREEN = 0x6E,
    INPUT_KEYBOARD_SCANCODE_PAUSE = 0x6F,
    INPUT_KEYBOARD_SCANCODE_LMETA = 0x70,
    INPUT_KEYBOARD_SCANCODE_RMETA = 0x71,
    INPUT_KEYBOARD_SCANCODE_MENU = 0x72,
} input_keyboard_scancode_t;

typedef struct
{
    input_keyboard_scancode_t scancode;
    input_keyboard_action_t action;
} input_keyboard_event_t;

typedef enum : uint8_t {
    INPUT_MOUSE_BUTTON_LEFT = 0x01,
    INPUT_MOUSE_BUTTON_RIGHT = 0x02,
    INPUT_MOUSE_BUTTON_MIDDLE = 0x04,
} input_mouse_button_t;

typedef struct
{
    int32_t x;
    int32_t y;
    int8_t delta_x;
    int8_t delta_y;
    uint8_t buttons;
} input_mouse_event_t;

typedef struct
{
    input_event_type_t type;
    uint8_t reserved;
    uint16_t reserved2;
    union {
        input_keyboard_event_t keyboard;
        input_mouse_event_t mouse;
    } data;
} input_event_t;

/*
 * Poll for input events. Returns 0 on event, 1 if none.
 */
static inline int poll_input_event(input_event_t *event)
{
    return syscall1(SYSCALL_POLL_INPUT_EVENT, (long) event);
}
