/*
 * Copyright (c) 2025, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#define SYSCALL_EXIT 0
#define SYSCALL_REQUEST_FB 1
#define SYSCALL_GET_KEYBOARD_STATE 2
#define SYSCALL_GET_MOUSE_STATE 3
#define SYSCALL_FILE_OPEN 4
#define SYSCALL_FILE_CLOSE 5
#define SYSCALL_FILE_CREATE 6
#define SYSCALL_FILE_REMOVE 7
#define SYSCALL_FILE_READ 8
#define SYSCALL_FILE_WRITE 9
#define SYSCALL_FILE_SEEK 10
#define SYSCALL_FILE_GETDENTS 11
#define SYSCALL_FILE_GETSTATS 12
#define SYSCALL_FILE_TELL 13
#define SYSCALL_GETDRIVES 14
#define SYSCALL_SLEEP 15
#define SYSCALL_GET_TICKS 16
#define SYSCALL_ALLOC_PAGES 17
