/*
 * Copyright (c) 2025, Ibrahim KAIKAA <ibrahimkaikaa@gmail.com>
 * SPDX-License-Identifier: GPL-3.0
 */

#pragma once

#define SYSCALL_EXIT 0
#define SYSCALL_REQUEST_FB 1
#define SYSCALL_POLL_INPUT_EVENT 2
#define SYSCALL_FILE_OPEN 3
#define SYSCALL_FILE_CLOSE 4
#define SYSCALL_FILE_CREATE 5
#define SYSCALL_FILE_REMOVE 6
#define SYSCALL_FILE_READ 7
#define SYSCALL_FILE_WRITE 8
#define SYSCALL_FILE_SEEK 9
#define SYSCALL_FILE_GETDENTS 10
#define SYSCALL_FILE_GETSTATS 11
#define SYSCALL_FILE_TELL 12
#define SYSCALL_GETDRIVES 13
#define SYSCALL_SLEEP 14
#define SYSCALL_GET_TICKS 15
#define SYSCALL_ALLOC_PAGES 16
#define SYSCALL_SPAWN_TASK 17
#define SYSCALL_TEST 18
