LIB_NAME := libui
STB_DIR := ../../../libs/stb

LIB_INCLUDE_DIRS := include ../libc/include ../libgfx/include ../libui/include ../libdesktop/include $(STB_DIR)
LIB_OPTFLAGS := -O0

include ../common-lib.mk
